// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-candidates.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_candidates_default = defineTool({
  name: "list_candidates",
  title: "List candidates",
  description: "List candidates on the signed-in recruiter's desk. Optional filters: text search across name/title/employer, location, minimum salary, and status. Results are capped at 50.",
  inputSchema: {
    search: z.string().optional().describe("Free text matched against name, current job title, and current employer."),
    location: z.string().optional().describe("Substring match on candidate location."),
    min_salary: z.number().optional().describe("Minimum salary expectation."),
    status: z.string().optional().describe("Exact candidate status (e.g. Active, Placed, Uncontacted)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return, default 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, location, min_salary, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client(ctx).from("candidates").select("id,name,current_job_title,current_employer,location,salary_expectation,status,email,linkedin_url,note,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search) q = q.or(`name.ilike.%${search}%,current_job_title.ilike.%${search}%,current_employer.ilike.%${search}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    if (typeof min_salary === "number") q = q.gte("salary_expectation", min_salary);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_jobs_default = defineTool2({
  name: "list_jobs",
  title: "List jobs",
  description: "List jobs on the signed-in recruiter's desk. Optional filters: status (Active, On Hold, Filled, Closed), text search across title, and client id. Results are capped at 50.",
  inputSchema: {
    status: z2.string().optional().describe("Filter by job status."),
    search: z2.string().optional().describe("Substring match on job title."),
    client_id: z2.string().uuid().optional().describe("Filter by client id."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, search, client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client2(ctx).from("jobs").select("id,title,status,location,salary_min,salary_max,client_id,description,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (search) q = q.ilike("title", `%${search}%`);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "List clients",
  description: "List clients on the signed-in recruiter's desk. Optional text search on company name.",
  inputSchema: {
    search: z3.string().optional().describe("Substring match on company name."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client3(ctx).from("clients").select("id,company_name,status,industry,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search) q = q.ilike("company_name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_note_default = defineTool4({
  name: "create_note",
  title: "Create note",
  description: "Add a note attached to a candidate, job, client, or contact on the signed-in recruiter's desk. Exactly one of candidate_id, job_id, client_id, or contact_id must be provided.",
  inputSchema: {
    content: z4.string().min(1).describe("The note body."),
    candidate_id: z4.string().uuid().optional(),
    job_id: z4.string().uuid().optional(),
    client_id: z4.string().uuid().optional(),
    contact_id: z4.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, candidate_id, job_id, client_id, contact_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const targets = [candidate_id, job_id, client_id, contact_id].filter(Boolean).length;
    if (targets !== 1) {
      return {
        content: [{ type: "text", text: "Provide exactly one of candidate_id, job_id, client_id, or contact_id." }],
        isError: true
      };
    }
    const { data, error } = await client4(ctx).from("notes").insert({
      content,
      candidate_id: candidate_id ?? null,
      job_id: job_id ?? null,
      client_id: client_id ?? null,
      contact_id: contact_id ?? null,
      owner_user_id: ctx.getUserId()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Note saved (id: ${data.id}).` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xkwophgwfqauvaztokue";
var mcp_default = defineMcp({
  name: "desky-mcp",
  title: "Desky CRM",
  version: "0.1.0",
  instructions: "Tools for the Desky recruitment CRM. Use list_candidates, list_jobs, and list_clients to read data on the signed-in recruiter's desk, and create_note to attach a note to a candidate, job, client, or contact.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_candidates_default, list_jobs_default, list_clients_default, create_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
